# Trino catalog connecting to MSSQL localhost - SSI_Common database
connector.name=sqlserver
connection-url=jdbc:sqlserver://host.docker.internal:1433;databaseName=SSI_Common;encrypt=false;trustServerCertificate=true
connection-user=${ENV:MSSQL_EXPORT_USER}
connection-password=${ENV:MSSQL_EXPORT_PASSWORD}