name: "ssi_trading_analytics"
version: "1.0.0"
config-version: 2

profile: "ssi_trading_analytics"

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  ssi_trading_analytics:
    staging:
      bronze:
        +materialized: table
        +schema: bronze
        +tags: ["bronze"]
      silver:
        +materialized: table
        +schema: silver
        +tags: ["silver"]
    marts:
      +materialized: table
      +schema: gold
      dim:
        +tags: ["dimension"]
      fact:
        +tags: ["fact"]
      intermediate:
        +materialized: view
        +tags: ["intermediate"]
      reports:
        +materialized: table
        +database: ssi_report
        +schema: reporting
        +tags: ["report"]
