-- RAW: landing zone, written to by Airbyte (one schema per source connection, mirrors source tables 1:1).
-- ANALYTICS: written to by dbt (staging views per domain, then MARTS with dim/fact/report models).
USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS RAW
    COMMENT = 'EL landing zone loaded by Airbyte from the 4 SQL Server source databases + HR API';

CREATE SCHEMA IF NOT EXISTS RAW.COMMON;
CREATE SCHEMA IF NOT EXISTS RAW.EQUITY;
CREATE SCHEMA IF NOT EXISTS RAW.DERIVATIVES;
CREATE SCHEMA IF NOT EXISTS RAW.OEF;
CREATE SCHEMA IF NOT EXISTS RAW.HR;

CREATE DATABASE IF NOT EXISTS ANALYTICS
    COMMENT = 'dbt-managed transform layer: staging views + MARTS (dim/fact/report models)';

CREATE SCHEMA IF NOT EXISTS ANALYTICS.STG_COMMON;
CREATE SCHEMA IF NOT EXISTS ANALYTICS.STG_EQUITY;
CREATE SCHEMA IF NOT EXISTS ANALYTICS.STG_DERIVATIVES;
CREATE SCHEMA IF NOT EXISTS ANALYTICS.STG_OEF;
CREATE SCHEMA IF NOT EXISTS ANALYTICS.STG_HR;
CREATE SCHEMA IF NOT EXISTS ANALYTICS.MARTS;

GRANT USAGE ON DATABASE RAW TO ROLE LOADER_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE RAW TO ROLE LOADER_ROLE;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE RAW TO ROLE LOADER_ROLE;

GRANT USAGE ON DATABASE RAW TO ROLE TRANSFORM_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RAW TO ROLE TRANSFORM_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE RAW TO ROLE TRANSFORM_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE RAW TO ROLE TRANSFORM_ROLE;

GRANT USAGE ON DATABASE ANALYTICS TO ROLE TRANSFORM_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE ANALYTICS TO ROLE TRANSFORM_ROLE;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE ANALYTICS TO ROLE TRANSFORM_ROLE;

GRANT USAGE ON DATABASE ANALYTICS TO ROLE REPORTING_ROLE;
GRANT USAGE ON SCHEMA ANALYTICS.MARTS TO ROLE REPORTING_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS.MARTS TO ROLE REPORTING_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS.MARTS TO ROLE REPORTING_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA ANALYTICS.MARTS TO ROLE REPORTING_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS.MARTS TO ROLE REPORTING_ROLE;
